name: tweegramBot in Action

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout tweegramBot repository
        uses: actions/checkout@v3

      - name: Setting python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installing python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setting environmental variables and executing
        env:
          ENTITY: ${{ secrets.ENTITY }}
          USERNAME: ${{ secrets.USERNAME }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python src/main.py

      - name: Auto commit from GitHub Actions
        run: |
          git config --local user.email "<GITHUB USERNAME>@users.noreply.github.com"
          git config --local user.name "<GITHUB USERNAME>"
          git add -A
          git commit -m "Automated Commit"
          git push
